/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdesaoRouteImport } from './routes/adesao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvaliacaoAcademicaRouteImport } from './routes/avaliacao-academica'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermoInteresseRouteImport } from './routes/termo-interesse'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AcessoTokenRouteImport } from './routes/acesso.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdesaoRoute = AdesaoRouteImport.update({
  id: '/adesao',
  path: '/adesao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoAcademicaRoute = AvaliacaoAcademicaRouteImport.update({
  id: '/avaliacao-academica',
  path: '/avaliacao-academica',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermoInteresseRoute = TermoInteresseRouteImport.update({
  id: '/termo-interesse',
  path: '/termo-interesse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AcessoTokenRoute = AcessoTokenRouteImport.update({
  id: '/acesso/$token',
  path: '/acesso/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adesao': typeof AdesaoRoute
  '/auth': typeof AuthRoute
  '/avaliacao-academica': typeof AvaliacaoAcademicaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termo-interesse': typeof TermoInteresseRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/acesso/$token': typeof AcessoTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adesao': typeof AdesaoRoute
  '/auth': typeof AuthRoute
  '/avaliacao-academica': typeof AvaliacaoAcademicaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termo-interesse': typeof TermoInteresseRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/acesso/$token': typeof AcessoTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/adesao': typeof AdesaoRoute
  '/auth': typeof AuthRoute
  '/avaliacao-academica': typeof AvaliacaoAcademicaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termo-interesse': typeof TermoInteresseRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/acesso/$token': typeof AcessoTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adesao'
    | '/auth'
    | '/avaliacao-academica'
    | '/sitemap.xml'
    | '/termo-interesse'
    | '/admin'
    | '/acesso/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adesao'
    | '/auth'
    | '/avaliacao-academica'
    | '/sitemap.xml'
    | '/termo-interesse'
    | '/admin'
    | '/acesso/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/adesao'
    | '/auth'
    | '/avaliacao-academica'
    | '/sitemap.xml'
    | '/termo-interesse'
    | '/_authenticated/admin'
    | '/acesso/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdesaoRoute: typeof AdesaoRoute
  AuthRoute: typeof AuthRoute
  AvaliacaoAcademicaRoute: typeof AvaliacaoAcademicaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermoInteresseRoute: typeof TermoInteresseRoute
  AcessoTokenRoute: typeof AcessoTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adesao': {
      id: '/adesao'
      path: '/adesao'
      fullPath: '/adesao'
      preLoaderRoute: typeof AdesaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao-academica': {
      id: '/avaliacao-academica'
      path: '/avaliacao-academica'
      fullPath: '/avaliacao-academica'
      preLoaderRoute: typeof AvaliacaoAcademicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termo-interesse': {
      id: '/termo-interesse'
      path: '/termo-interesse'
      fullPath: '/termo-interesse'
      preLoaderRoute: typeof TermoInteresseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/acesso/$token': {
      id: '/acesso/$token'
      path: '/acesso/$token'
      fullPath: '/acesso/$token'
      preLoaderRoute: typeof AcessoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdesaoRoute: AdesaoRoute,
  AuthRoute: AuthRoute,
  AvaliacaoAcademicaRoute: AvaliacaoAcademicaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermoInteresseRoute: TermoInteresseRoute,
  AcessoTokenRoute: AcessoTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
